export const store = {
  books: [
    {
      id: 1,
      title: 'Clean Code',
      author: { name: 'Robert C. Martin' },
      price: 17.96,
    },
    {
      id: 2,
      title: 'Maintainable JavaScript',
      author: { name: 'Nicholas C. Zakas' },
      price: 10,
    },
    {
      id: 3,
      title: 'Agile Software Development',
      author: { name: 'Robert C. Martin' },
      editor: { name: 'Yussef Miller' },
      price: 20,
    },
    {
      id: 4,
      title: 'JavaScript: The Good Parts',
      author: { name: 'Douglas Crockford' },
      price: 15.67,
    },
  ],
  bicycle: {
    color: 'red',
    price: 19.95,
  },
  software: {
    id: 1,
    title: 'jsonpath-mapper',
    author: { name: 'Neil Flatley' },
    cost: 0.0,
  },
};

export const nullSearchPayload = {
  duration: 16748.44500000472,
  facet: 'postgraduate-courses',
  pageIndex: 0,
  payload: null,
  preload: true,
};

export const mapArrayObject = {
  activePaymentMethod: 'paypal_payment',
  basketItems: [
    {
      name: 'Revitive Medic',
      image: '/image-library-de/medic-products.x09f928dd.jpg',
      price: '209.24',
      itemId: '2298-RMV-DE',
      id: '3298',
      quantity: 2,
    },
  ],
  basketItemsCount: 2,
  basketPath: '/de/basket',
  billingAddress: {
    city: 'Waldfeucht',
    country: 'Germany',
    country_iso_2: 'DE',
    country_iso_3: 'DEU',
    line1: 'Talstr. 123',
    line2: '',
    postal_code: '52525',
    state: 'Nordrhein-Westfalen',
    provinceCode: 'Nordrhein-Westfalen',
    provinceName: 'Nordrhein-Westfalen',
  },
  checkoutPath: '/de/checkout',
  currency: '€',
  currencyString: 'EUR',
  customerDetails: {
    email: 'neilflatley@hotmail.com',
    first_name: 'Neil',
    last_name: 'Flatley',
    phone: '447725665614',
  },
  defaultTaxAmount: 39.76,
  defaultTaxRate: 0.19,
  discountValue: null,
  installmentValue: '458.24',
  marketingConsent: false,
  orderAmount: 458.24,
  shipping: 0,
  shippingAddress: {
    city: 'Waldfeucht',
    country: 'Germany',
    country_iso_2: 'DE',
    country_iso_3: 'DEU',
    line1: 'Talstr. 123',
    line2: '',
    postal_code: '52525',
    state: 'Nordrhein-Westfalen',
    provinceCode: 'Nordrhein-Westfalen',
    provinceName: 'Nordrhein-Westfalen',
  },
  shippingMethod: {
    shipMethodCode: '2217',
    method: 'Kostenlose Lieferung (3-5 Werktage)',
    price: 0,
  },
  shippingMethods: [
    {
      shipMethodCode: '2217',
      method: 'Kostenlose Lieferung (3-5 Werktage)',
      shippingRule: [
        {
          basketValue: 49.99,
          rule: 'Greater than',
        },
      ],
      price: 0,
    },
  ],
  splitPayment: false,
  subsidiary: '4',
  subTotal: 418.48,
  taxAmount: 39.76,
  taxRate: 0.19,
  totalPlusTax: 458.24,
  webstore: 'revitiveGermany',
  currentLang: 'de-de',
  dictionary: {
    path: 'de',
    label: 'German',
    availableLanguages: null,
    currency: 'EUR',
    country: 'DE',
    country_iso_3: 'DEU',
    stateDropdown: false,
    currencyPosition: 'after',
  },
  languagePath: 'de',
};

export const queryParamsToCourseApi = {
  selectedFilters: {
    cluster: '',
    'study-options': '',
    location: '257fa015-8170-4689-8166-f55f1aaa78f0',
    'start-date': '',
  },
  pageIndex: 0,
  orderBy: ['entryTitle'],
  contentTypeIds: ['course'],
  linkDepth: 3,
  versionStatus: 'latest',
  pageSize: 12,
  projectId: 'website',
  searchTerm: '',
  webpageTemplates: [],
  customWhere: [],
  weightedSearchFields: [
    { fieldId: 'entryTitle', weight: 100 },
    { fieldId: 'title', weight: 100 },
    { fieldId: 'sys.uri', weight: 100 },
  ],
  fields: [
    'sys',
    'title',
    'entryTitle',
    'entryYears',
    'entryYear',
    'year',
    'courseImagery',
    'primaryImage',
    'awardLevel',
    'courseLevel',
  ],
  filters: [
    { expressionType: 'contentType', value: [] },
    { expressionType: 'contentType', value: [] },
    {
      expressionType: 'contentType',
      key: 'sys.contentTypeId',
      value: ['257fa015-8170-4689-8166-f55f1aaa78f0'],
    },
    { expressionType: 'contentType', value: [] },
  ],
};

export const getQuery = {
  fields: 'sys,title,description,thumbnail',
  orderBy: '[{"desc":"sys.version.published"},{"desc":"sys.version.modified"}]',
  pageIndex: '0',
  pageSize: '12',
  where:
    '[{"field":"sys.versionStatus","equalTo":"latest"},{"or":[{"and":[{"field":"sys.metadata.includeInSearch","exists":true},{"field":"sys.metadata.includeInSearch","equalTo":true}]},{"field":"sys.metadata.includeInSearch","exists":false}]},{"and":[{"field":"sys.dataFormat","equalTo":"webpage"},{"not":[{"field":"sys.contentTypeId","equalTo":"newCoursesWebpage"}]}]}]',
  whereArr: [
    { field: 'sys.versionStatus', equalTo: 'latest' },
    {
      or: [
        {
          and: [
            { field: 'sys.metadata.includeInSearch', exists: true },
            { field: 'sys.metadata.includeInSearch', equalTo: true },
          ],
        },
        { field: 'sys.metadata.includeInSearch', exists: false },
      ],
    },
    {
      and: [
        { field: 'sys.dataFormat', equalTo: 'webpage' },
        {
          not: [{ field: 'sys.contentTypeId', equalTo: 'newCoursesWebpage' }],
        },
      ],
    },
  ],
};

export const siteConfigEntry = {
  mainNavigation: [
    {
      offers: [],
      children: [],
      itemLink: {
        sys: {
          dataFormat: 'entry',
          contentTypeId: 'homePage',
          language: 'en-CA',
          id: 'c399515c-9094-43c7-9215-8bf2735e5a29',
          uri: '/ca',
          version: { published: '2021-01-14T09:42:29.0248495Z' },
          versionStatus: 'latest',
          slug: 'home-1',
        },
        title: 'Home',
        entryTitle: 'Home',
      },
      sys: {
        dataFormat: 'entry',
        contentTypeId: 'navigationItem',
        language: 'en-CA',
        id: '08aacefe-1af2-412e-9456-8776266ef5cc',
        uri: null,
        version: { published: '2021-01-06T06:40:32.9801364Z' },
        versionStatus: 'latest',
        slug: 'home',
      },
      title: 'Home',
      entryTitle: 'Home',
    },
    {
      offers: [
        {
          ctaText: 'Buy now',
          subTitle: 'Gold Package',
          accentColor: 'Red',
          specialOffer: {
            image: [
              {
                altText: 'Medic and Electrode body pads',
                transformations: null,
                caption: '',
                asset: {
                  description: null,
                  sys: {
                    dataFormat: 'asset',
                    contentTypeId: 'image',
                    language: 'en-CA',
                    id: 'dd2a8b8d-506f-4251-8764-a824bb14501c',
                    uri: '/image-library-ca/medic-offers.x05124733.png',
                    version: { published: null },
                    versionStatus: 'latest',
                    slug: null,
                  },
                  title: 'medic_offers',
                  entryTitle: 'medic_offers',
                },
              },
            ],
            price: '299',
            description:
              '<ul>\n<li><strong>1&nbsp;</strong>Revitive Medic</li>\n<li><strong>3</strong> Year Gold Warranty</li>\n<li><strong> 1</strong> Bonus pack of body pads</li>\n<li>Free Delivery</li>\n</ul>',
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'specialOffer',
              language: 'en-CA',
              id: 'fdd01cc5-2319-4033-9823-fc838a01785e',
              uri: null,
              version: { published: '2021-01-14T17:06:17.8691144Z' },
              versionStatus: 'latest',
              slug: 'revitive-medic-platinum-bundle-test-copy',
            },
            netsuiteProduct: {
              unitPrice: 299,
              sys: {
                dataFormat: 'entry',
                contentTypeId: 'netSuiteProduct',
                language: 'en-CA',
                id: '447a3b10-bc83-4b17-89d0-60ee37a882a6',
                uri: null,
                version: { published: '2021-01-06T16:54:36.207644Z' },
                versionStatus: 'latest',
                slug: '2297-rmv-ca-currency-6-price-level-5-price-299.00',
              },
              title: '2297-RMV-CA, Currency: 6, Price level: 5, Price: 299.00',
              sku: '2472',
              entryTitle:
                '2297-RMV-CA, Currency: 6, Price level: 5, Price: 299.00',
            },
            entryTitle: 'Revitive Medic Gold Package',
          },
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'specialOfferCard',
            language: 'en-CA',
            id: 'c847455b-f1d2-4957-a18b-bee15ad01571',
            uri: null,
            version: { published: '2021-01-14T17:15:13.6662432Z' },
            versionStatus: 'latest',
            slug: 'revitive-medic-gold-package-deal',
          },
          title: 'Revitive Medic',
          specialOfferHighlight: [
            {
              offerBenefit: '3-Year Warranty',
              benefitBackground: 'Orange fill',
              showRight: false,
            },
            {
              offerBenefit: 'Bonus $25',
              benefitBackground: 'Red fill',
              showRight: false,
            },
          ],
          entryTitle: 'Revitive Medic Gold Package Deal',
          offerStrapline: 'Best Deal',
        },
        {
          ctaText: 'Buy Now',
          subTitle: 'Complete Pain Management Pack',
          accentColor: 'Red',
          specialOffer: {
            image: [
              {
                altText: 'Revitive Medic',
                transformations: null,
                caption: '',
                asset: {
                  description: null,
                  sys: {
                    dataFormat: 'asset',
                    contentTypeId: 'image',
                    language: 'en-CA',
                    id: '442cde14-797a-480e-8562-e195c0d698d5',
                    uri: '/image-library-ca/revitive-medic.x697c74e8.png',
                    version: {
                      published: '2020-11-10T11:39:37.2784304Z',
                    },
                    versionStatus: 'latest',
                    slug: null,
                  },
                  title: 'revitive-medic',
                  entryTitle: 'revitive-medic',
                },
              },
            ],
            price: null,
            description:
              '<ul>\n<li>Revitive Medic GWP 1Pay Platinum Pack</li>\n<li>1 x revitive medic</li>\n<li>3 x body pads</li>\n<li>1 x carry bagFree shipping</li>\n<li>3 year warranty</li>\n</ul>',
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'specialOffer',
              language: 'en-CA',
              id: 'fb43431a-c3db-4d36-a969-04f4c9cc269d',
              uri: '/ca/special-offers/revitive-medic-platinum-bundle-test',
              version: { published: '2021-01-11T13:05:47.135983Z' },
              versionStatus: 'latest',
              slug: 'platinum-bundle-test',
            },
            netsuiteProduct: {
              unitPrice: 317.29,
              sys: {
                dataFormat: 'entry',
                contentTypeId: 'netSuiteProduct',
                language: 'en-CA',
                id: '25d503d0-b641-41dc-86e7-76c54a7321e9',
                uri: null,
                version: { published: '2020-12-22T12:50:04.0997666Z' },
                versionStatus: 'latest',
                slug:
                  'med-blkt-1pay-plat-ca-currency-6-price-level-5-price-317.29',
              },
              title:
                'MED-BLKT-1PAY-PLAT-CA, Currency: 6, Price level: 5, Price: 317.29',
              sku: '3423',
              entryTitle:
                'MED-BLKT-1PAY-PLAT-CA, Currency: 6, Price level: 5, Price: 317.29',
            },
            entryTitle: 'Revitive Medic Platinum Bundle TEST',
          },
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'specialOfferCard',
            language: 'en-CA',
            id: 'f900ffc4-d45f-447c-be98-797ab6e2476b',
            uri: null,
            version: { published: '2021-01-13T13:21:13.0183779Z' },
            versionStatus: 'latest',
            slug: 'revitive-medic-platinum-bundle-test',
          },
          title: 'Medic',
          specialOfferHighlight: [
            {
              offerBenefit: 'Save £104',
              benefitBackground: 'Orange fill',
              showRight: false,
            },
            {
              offerBenefit: '3-year Warranty',
              benefitBackground: 'Red fill',
              showRight: true,
            },
          ],
          entryTitle: 'Revitive Medic Platinum Bundle TEST',
          offerStrapline: 'Best Deal',
        },
      ],
      children: [
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'productListingPage',
            language: 'en-CA',
            id: 'af1c8896-2fc0-48ad-82b1-b60afa45e263',
            uri: '/ca/products',
            version: { published: '2021-01-14T15:25:22.937703Z' },
            versionStatus: 'latest',
            slug: 'revitive-circulation-booster',
          },
          title: 'All products',
          entryTitle: 'All products',
        },
        {
          image: [
            {
              altText: 'Revitive IX',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: '84641f6a-a702-4149-9779-08bf05aaa265',
                  uri: '/image-library-ca/revitive-ix1.x54dc9796.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'revitive-ix',
                entryTitle: 'revitive-ix',
              },
            },
          ],
          price: null,
          description:
            '<h3>Revitive IX may help:</h3>\n<ul>\n<li>Actively improves circulation</li>\n<li>Relieves pain and cramps</li>\n<li>Reduces swelling</li>\n<li>Strengthens leg muscles</li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: '5ca54051-bbe3-43cc-be0b-9516a478883c',
            uri: '/ca/products/revitive-prod-ix',
            version: { published: '2021-01-14T15:20:34.6141972Z' },
            versionStatus: 'latest',
            slug: 'revitive-ix-3',
          },
          netsuiteProduct: {
            unitPrice: 299,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: '447a3b10-bc83-4b17-89d0-60ee37a882a6',
              uri: null,
              version: { published: '2021-01-06T16:54:36.207644Z' },
              versionStatus: 'latest',
              slug: '2297-rmv-ca-currency-6-price-level-5-price-299.00',
            },
            title: '2297-RMV-CA, Currency: 6, Price level: 5, Price: 299.00',
            sku: '2472',
            entryTitle:
              '2297-RMV-CA, Currency: 6, Price level: 5, Price: 299.00',
          },
          entryTitle: 'Revitive IX',
        },
        {
          image: [
            {
              altText: 'Revitive Medic',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: 'ac772751-0da0-435f-b6cc-9ea731e88ad0',
                  uri: '/image-library-ca/revitive-medic1.x31712462.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'revitive-medic',
                entryTitle: 'revitive-medic',
              },
            },
          ],
          price: null,
          description:
            '<h3>Revitive Medic may help:</h3>\n<ul>\n<li>Reduce pain in legs and feet</li>\n<li>Reduce swollen feet and ankles</li>\n<li><span style="font-size: 14px;">Alleviate tired, aching legs &amp; feet</span></li>\n<li><span style="font-size: 14px;">Actively improve circulation</span></li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: '6c63c695-b7b7-4a6c-bfe6-e8ed1536a488',
            uri: '/ca/products/revitive-medic',
            version: { published: '2021-01-14T15:17:40.5220697Z' },
            versionStatus: 'latest',
            slug: 'revitive-medic',
          },
          netsuiteProduct: {
            unitPrice: 299.96,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: 'b58bbd37-d490-4412-8f22-69767fdf1b7d',
              uri: null,
              version: { published: '2021-01-06T12:46:32.7057874Z' },
              versionStatus: 'latest',
              slug: '4469-rmv-ca-currency-6-price-level-5-price-212.92',
            },
            title: '4469-RMV-CA, Currency: 6, Price level: 5, Price: 299.96',
            sku: '4470',
            entryTitle:
              '4469-RMV-CA, Currency: 6, Price level: 5, Price: 299.96',
          },
          entryTitle: 'Revitive Medic',
        },
        {
          image: [
            {
              altText: 'Revitive Cream',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: 'ede792b7-5840-48b4-abdc-3152bd9b19dd',
                  uri: '/image-library-ca/cream.x484e180f.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'cream',
                entryTitle: 'cream',
              },
            },
          ],
          price: null,
          description:
            '<p><strong>A specially formulated foot cream to hydrate and relieve extremely dry, cracked feet.</strong></p>\n<p>Revitive foot and leg cream has been specially formulated to enable the electrical stimulation emitted from the footpads of the Revitive circulation booster to pass even easily through your skin. These electrical currents then pass and into your leg muscles which results in a bigger and better muscle contraction.</p>\n<p>When used daily the Revitive foot and leg cream will instantly boost the hydration levels of your skin as well as help to relieve extremely dry, cracked feet. This cream should be used before each use of the Revitive circulation boosters to maximise the affects.</p>\n<h3>Features of Revitive foot and leg cream 170ml</h3>\n<ul>\n<li>Aids with bigger and better muscle contractions</li>\n<li>Relieves dry and cracked skin</li>\n<li>Maximises the effects of the Revitive circulation boosters</li>\n<li>Increases the hydration levels of the skin on your legs and feet</li>\n<li>Allows for electrical stimulation to more easily pass through your skin</li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: 'a93a7529-9a34-4985-92fb-b5582fee3614',
            uri: '/ca/accessories/revitive-cream',
            version: { published: '2021-01-14T09:57:59.8573454Z' },
            versionStatus: 'latest',
            slug: 'revitive-cream',
          },
          netsuiteProduct: {
            unitPrice: 9.99,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: '751957e1-fbe9-4d9a-8620-6d86363d11b5',
              uri: null,
              version: { published: '2021-01-06T12:46:29.2523201Z' },
              versionStatus: 'latest',
              slug: '2679-rev-cream-ca-currency-6-price-level-5-price-9.99',
            },
            title:
              '2679-REV-CREAM-CA, Currency: 6, Price level: 5, Price: 9.99',
            sku: '4408',
            entryTitle:
              '2679-REV-CREAM-CA, Currency: 6, Price level: 5, Price: 9.99',
          },
          entryTitle: 'Revitive Cream',
        },
        {
          image: [
            {
              altText: 'Revitive Electrode Body Pads',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: '17454855-c24a-45ac-a09f-5ab4b64914a2',
                  uri: '/image-library-ca/bodypads.x5e1c9b0b.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'bodypads',
                entryTitle: 'bodypads',
              },
            },
          ],
          price: null,
          description:
            '<p>Replacement Revitive Body Pads can be used with Revitive IX, CX &amp; LV.</p>\n<p>When used with Revitive, the Body Pads apply Electrical Muscle Stimulation (EMS) to stimulate the nerve endings causing the muscles to gently contract. The pads allow targeting of specific areas of the body, such as lower back, upper back, knees, thighs &amp; arms.</p>\n<ul>\n<li>Reusable up to 20 &ndash; 30 applications</li>\n<li>Easy to apply</li>\n<li>Can also be used with the Original Circulation Booster v3</li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: '421e575d-e681-495b-987a-a0a88188660a',
            uri: '/ca/accessories/revitive-tens-body-pads',
            version: { published: '2021-01-14T09:57:46.6591795Z' },
            versionStatus: 'latest',
            slug: 'revitive-electrode-body-pads',
          },
          netsuiteProduct: {
            unitPrice: 24.95,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: 'bc3f490f-c3da-4cd5-891c-d73df4a8865f',
              uri: null,
              version: { published: '2021-01-06T16:51:33.1692972Z' },
              versionStatus: 'latest',
              slug: '2044-rev-pads-ca-currency-6-price-level-5-price-24.95',
            },
            title:
              '2044-REV-PADS-CA, Currency: 6, Price level: 5, Price: 24.95',
            sku: '2519',
            entryTitle:
              '2044-REV-PADS-CA, Currency: 6, Price level: 5, Price: 24.95',
          },
          entryTitle: 'Revitive Electrode Body Pads',
        },
        {
          image: [
            {
              altText: 'Remote control IX',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: '812b8d29-cbfa-4a4a-875a-cc19977927d3',
                  uri: '/image-library-ca/remoteix.x1317316f.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'remoteIX',
                entryTitle: 'remoteIX',
              },
            },
          ],
          price: null,
          description:
            '<p>Replacement remote control for your Revitive. Suitable for the following Revitive:</p>\n<ul>\n<li>Revitive IX</li>\n<li>Revitive Circulation Booster V3</li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: '4bb4b0d5-054a-4321-a540-99ef5e5930e9',
            uri: '/ca/accessories/revitive-remote',
            version: { published: '2021-01-14T09:57:38.9048313Z' },
            versionStatus: 'latest',
            slug: 'revitive-ix-remote-control',
          },
          netsuiteProduct: {
            unitPrice: 10,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: '82184197-370a-423c-8bf4-6679a0c14cc4',
              uri: null,
              version: { published: '2021-01-06T11:42:37.4213466Z' },
              versionStatus: 'latest',
              slug: 'rix-remote-ca-currency-6-price-level-5-price-8.61',
            },
            title: 'RIX-REMOTE-CA, Currency: 6, Price level: 5, Price: 10.00',
            sku: '1522',
            entryTitle:
              'RIX-REMOTE-CA, Currency: 6, Price level: 5, Price: 10.00',
          },
          entryTitle: 'Revitive IX Remote Control',
        },
        {
          image: [
            {
              altText: 'Revitive Adaptor',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: '99c11b51-a0b4-40ce-a9e0-d0b60c3a41c6',
                  uri: '/image-library-ca/adaptor.x39a01deb.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'adaptor',
                entryTitle: 'adaptor',
              },
            },
          ],
          price: null,
          description:
            '<p>Replacement or additional power source for your Revitive. Fits for the following models:</p>\n<ul>\n<li>Revitive IX</li>\n<li>Revitive LV</li>\n<li>Revitive Circulation Booster V3</li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: 'fc3b6f76-7f59-4f2e-8b76-06491e5b5f47',
            uri: '/ca/accessories/adaptor',
            version: { published: '2021-01-14T09:57:30.62278Z' },
            versionStatus: 'latest',
            slug: 'revitive-power-adaptor',
          },
          netsuiteProduct: {
            unitPrice: 16,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: '0c677c08-638d-48ae-8612-98bac98533ce',
              uri: null,
              version: { published: '2021-01-06T11:42:32.291771Z' },
              versionStatus: 'latest',
              slug: 'revitive-adaptor-ca-currency-6-price-level-5-price-14.17',
            },
            title:
              'REVITIVE-ADAPTOR-CA, Currency: 6, Price level: 5, Price: 16.00',
            sku: '1038',
            entryTitle:
              'REVITIVE-ADAPTOR-CA, Currency: 6, Price level: 5, Price: 16.00',
          },
          entryTitle: 'Revitive Power Adaptor',
        },
        {
          image: [
            {
              altText: 'Revitive Bag',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: '9eab22eb-e062-4cf0-97d6-2729c9077830',
                  uri: '/image-library-ca/bag.xa7458d5d.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'bag',
                entryTitle: 'bag',
              },
            },
          ],
          price: null,
          description:
            '<p>Introducing the Revitive Circulation Booster storage bag. Store your Revitive&nbsp;and accessories all together in this quality storage bag.</p>\n<p>Use with any of our Circulation Boosters:</p>\n<ul>\n<li>Revitive IX</li>\n<li>Revitive LV</li>\n<li>Revitive Circulation Booster</li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: '9b7fc3af-a23b-4bee-a6bd-9bdaeb8b4ae4',
            uri: '/ca/accessories/storage-bag',
            version: { published: '2021-01-14T09:57:18.4347276Z' },
            versionStatus: 'latest',
            slug: 'revitive-storage-bag',
          },
          netsuiteProduct: {
            unitPrice: 59.99,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: 'c2f9c9fa-a0b7-4aee-897a-70c267b0f4be',
              uri: null,
              version: { published: '2021-01-06T11:42:18.2467539Z' },
              versionStatus: 'latest',
              slug: '1102-rev-bag-ca-currency-6-price-level-5-price-50.05',
            },
            title: '1102-REV-BAG-CA, Currency: 6, Price level: 5, Price: 59.99',
            sku: '1265',
            entryTitle:
              '1102-REV-BAG-CA, Currency: 6, Price level: 5, Price: 59.99',
          },
          entryTitle: 'Revitive Storage Bag',
        },
      ],
      itemLink: null,
      sys: {
        dataFormat: 'entry',
        contentTypeId: 'navigationItem',
        language: 'en-CA',
        id: '7bb05862-5902-451d-8ca6-b6b11f7cf9b1',
        uri: null,
        version: { published: '2021-01-14T08:21:09.4601009Z' },
        versionStatus: 'latest',
        slug: 'products',
      },
      title: 'Products',
      entryTitle: 'Products',
    },
    {
      offers: [],
      children: [
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'landingPage',
            language: 'en-CA',
            id: '77ea3e58-1eac-48be-8549-fd27b853bc4f',
            uri: '/ca/how-can-revitive-help-you',
            version: { published: '2021-01-07T12:26:48.022916Z' },
            versionStatus: 'latest',
            slug: 'how-can-revitive-help-you',
          },
          title: 'How can Revitive help you?',
          entryTitle: 'How can Revitive help you?',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'symptom',
            language: 'en-CA',
            id: 'da5d9f9e-88c2-47a5-b214-90f114ccd607',
            uri: '/ca/symptoms/poor-circulation',
            version: { published: '2021-01-13T09:39:22.2647777Z' },
            versionStatus: 'latest',
            slug: 'poor-circulation-1',
          },
          title: 'Poor Circulation',
          entryTitle: 'Poor Circulation',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'symptom',
            language: 'en-CA',
            id: 'a307a077-ae17-4344-8577-eb4058cc5f1a',
            uri: '/ca/symptoms/leg-pain',
            version: { published: '2021-01-08T09:01:06.5975549Z' },
            versionStatus: 'latest',
            slug: 'poor-mobility',
          },
          title: 'Leg Pain',
          entryTitle: 'Leg Pain',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'symptom',
            language: 'en-CA',
            id: 'abf7611b-d12b-4b37-ba08-0463a0a99e75',
            uri: '/ca/symptoms/swollen-feet',
            version: { published: '2021-01-12T09:01:47.773789Z' },
            versionStatus: 'latest',
            slug: 'swollen-feet-ankles',
          },
          title: 'Swelling',
          entryTitle: 'Swelling',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'symptom',
            language: 'en-CA',
            id: 'dc178f26-6da7-4d10-ab33-7098ae29fa53',
            uri: '/ca/symptoms/neuropathy',
            version: { published: '2021-01-14T09:06:41.9452822Z' },
            versionStatus: 'latest',
            slug: 'are-you-suffering-from-peripheral-neuropathy',
          },
          title: 'Neuropathic Pain',
          entryTitle: 'Neuropathic Pain',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'symptom',
            language: 'en-CA',
            id: '5e67da0a-8c20-4ba2-a4af-56f5273d24f9',
            uri: '/ca/symptoms/arthritis',
            version: { published: '2021-01-08T09:51:41.5711893Z' },
            versionStatus: 'latest',
            slug: 'osteoarthritis',
          },
          title: 'Osteoarthritis',
          entryTitle: 'Osteoarthritis',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'symptom',
            language: 'en-CA',
            id: 'c1a23d1b-ab6d-4230-b934-13e6e52c3141',
            uri: '/ca/symptoms/diabetes',
            version: { published: '2021-01-07T14:37:16.2061251Z' },
            versionStatus: 'latest',
            slug: 'diabetes',
          },
          title: 'Diabetes',
          entryTitle: 'Diabetes',
        },
      ],
      itemLink: {
        sys: {
          dataFormat: 'entry',
          contentTypeId: 'landingPage',
          language: 'en-CA',
          id: '77ea3e58-1eac-48be-8549-fd27b853bc4f',
          uri: '/ca/how-can-revitive-help-you',
          version: { published: '2021-01-07T12:26:48.022916Z' },
          versionStatus: 'latest',
          slug: 'how-can-revitive-help-you',
        },
        title: 'How can Revitive help you?',
        entryTitle: 'How can Revitive help you?',
      },
      sys: {
        dataFormat: 'entry',
        contentTypeId: 'navigationItem',
        language: 'en-CA',
        id: '3bdbb18e-3167-47ca-9d30-aa2708df07f0',
        uri: null,
        version: { published: '2021-01-12T08:58:57.9704228Z' },
        versionStatus: 'latest',
        slug: 'symptoms',
      },
      title: 'Symptoms',
      entryTitle: 'Symptoms',
    },
    {
      offers: [],
      children: [],
      itemLink: {
        sys: {
          dataFormat: 'entry',
          contentTypeId: 'specialOfferListingPage',
          language: 'en-CA',
          id: '8ae691f9-a948-4a72-869a-da02b3cbca37',
          uri: '/ca/special-offers',
          version: { published: '2021-01-14T16:41:02.9567552Z' },
          versionStatus: 'latest',
          slug: 'special-offers-1',
        },
        title: 'Special Offers',
        entryTitle: 'Special Offers',
      },
      sys: {
        dataFormat: 'entry',
        contentTypeId: 'navigationItem',
        language: 'en-CA',
        id: '930f2fb2-3900-4e8f-ae7f-f1ae4cba6bf8',
        uri: null,
        version: { published: '2021-01-13T12:23:53.071876Z' },
        versionStatus: 'latest',
        slug: 'offers',
      },
      title: 'Offers',
      entryTitle: 'Offers',
    },
  ],
  mailingListSignUp: {
    buttonText: 'Sign up',
    path: {
      sys: {
        dataFormat: 'entry',
        contentTypeId: 'landingPage',
        language: 'en-CA',
        id: '65c983a3-c48b-40da-8759-c87421b7f07e',
        uri: '/ca/sign-up',
        version: { published: '2021-01-13T17:05:47.1514838Z' },
        versionStatus: 'latest',
        slug: 'marketing-sign-up',
      },
      title: 'Marketing sign up',
      entryTitle: 'Marketing sign up',
    },
    text:
      'For free hints, tips & special offers, sign up using your email address',
    title: 'Sign up to our mailing list',
  },
  footerLegalText:
    '<p>Revitive Circulation Booster&reg; (all models) should not be used by people who are fitted with an electronic implant, such as a pacemaker or AICD, being treated for, or have the symptoms of, a deep vein thrombosis, or are pregnant.</p>\n<p>Revitive Circulation Booster&reg; is intended to help reduce symptoms of poor circulation. It is not intended to treat underlying medical conditions.</p>\n<p>The Revitive Guarantee includes free standard P&amp;P worth &pound;7.99 in England &amp; Wales. Some areas of Scotland, Northern Ireland and other remote postcodes will incur a surcharge cost of &pound;19.99 for standard delivery. Next day, Saturday or express deliveries cost more, please ask our customer service team for a quote. If returned within 90 days, full refund of purchase price, minus collection fee of &pound;7.99 (some areas of Scotland and other remote postcodes will incur a surcharge cost of &pound;19.99). A list of postcodes that fall within remote locations can be found on our delivery page.</p>\n<p>**Individual results may vary**</p>\n<p>All special offers and bundles are only available to customers residing in the UK</p>\n<p>Copyright &copy; 2021 Actegy Ltd. All rights reserved&nbsp;</p>\n<p>Revitive is a trading name of<br />Actegy Ltd, <br />Company Number 04819502, <br />Reflex, Cain Road, <br />Bracknell, RG12 1HL</p>',
  footerLinks: [
    {
      links: [
        {
          image: [
            {
              altText: 'Revitive Medic',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: 'ac772751-0da0-435f-b6cc-9ea731e88ad0',
                  uri: '/image-library-ca/revitive-medic1.x31712462.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'revitive-medic',
                entryTitle: 'revitive-medic',
              },
            },
          ],
          price: null,
          description:
            '<h3>Revitive Medic may help:</h3>\n<ul>\n<li>Reduce pain in legs and feet</li>\n<li>Reduce swollen feet and ankles</li>\n<li><span style="font-size: 14px;">Alleviate tired, aching legs &amp; feet</span></li>\n<li><span style="font-size: 14px;">Actively improve circulation</span></li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: '6c63c695-b7b7-4a6c-bfe6-e8ed1536a488',
            uri: '/ca/products/revitive-medic',
            version: { published: '2021-01-14T15:17:40.5220697Z' },
            versionStatus: 'latest',
            slug: 'revitive-medic',
          },
          netsuiteProduct: {
            unitPrice: 299.96,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: 'b58bbd37-d490-4412-8f22-69767fdf1b7d',
              uri: null,
              version: { published: '2021-01-06T12:46:32.7057874Z' },
              versionStatus: 'latest',
              slug: '4469-rmv-ca-currency-6-price-level-5-price-212.92',
            },
            title: '4469-RMV-CA, Currency: 6, Price level: 5, Price: 299.96',
            sku: '4470',
            entryTitle:
              '4469-RMV-CA, Currency: 6, Price level: 5, Price: 299.96',
          },
          entryTitle: 'Revitive Medic',
        },
        {
          image: [
            {
              altText: 'Revitive IX',
              transformations: null,
              caption: '',
              asset: {
                description: null,
                sys: {
                  dataFormat: 'asset',
                  contentTypeId: 'image',
                  language: 'en-CA',
                  id: '84641f6a-a702-4149-9779-08bf05aaa265',
                  uri: '/image-library-ca/revitive-ix1.x54dc9796.jpg',
                  version: { published: null },
                  versionStatus: 'latest',
                  slug: null,
                },
                title: 'revitive-ix',
                entryTitle: 'revitive-ix',
              },
            },
          ],
          price: null,
          description:
            '<h3>Revitive IX may help:</h3>\n<ul>\n<li>Actively improves circulation</li>\n<li>Relieves pain and cramps</li>\n<li>Reduces swelling</li>\n<li>Strengthens leg muscles</li>\n</ul>',
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'product',
            language: 'en-CA',
            id: '5ca54051-bbe3-43cc-be0b-9516a478883c',
            uri: '/ca/products/revitive-prod-ix',
            version: { published: '2021-01-14T15:20:34.6141972Z' },
            versionStatus: 'latest',
            slug: 'revitive-ix-3',
          },
          netsuiteProduct: {
            unitPrice: 299,
            sys: {
              dataFormat: 'entry',
              contentTypeId: 'netSuiteProduct',
              language: 'en-CA',
              id: '447a3b10-bc83-4b17-89d0-60ee37a882a6',
              uri: null,
              version: { published: '2021-01-06T16:54:36.207644Z' },
              versionStatus: 'latest',
              slug: '2297-rmv-ca-currency-6-price-level-5-price-299.00',
            },
            title: '2297-RMV-CA, Currency: 6, Price level: 5, Price: 299.00',
            sku: '2472',
            entryTitle:
              '2297-RMV-CA, Currency: 6, Price level: 5, Price: 299.00',
          },
          entryTitle: 'Revitive IX',
        },
      ],
      title: 'Products',
    },
    {
      links: [
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'contentPage',
            language: 'en-CA',
            id: '98090620-7949-461b-8607-8b3e3a6096a5',
            uri: '/ca/returns',
            version: { published: '2021-01-04T14:31:24.3593302Z' },
            versionStatus: 'latest',
            slug: 'returns-and-refunds',
          },
          title: 'Returns and Refunds',
          entryTitle: 'Returns and Refunds',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'contentPage',
            language: 'en-CA',
            id: '15dd0a48-7411-4057-86eb-971af67de493',
            uri: '/ca/delivery',
            version: { published: '2021-01-04T14:27:44.8460602Z' },
            versionStatus: 'latest',
            slug: 'shipping',
          },
          title: 'Shipping',
          entryTitle: 'Shipping',
        },
      ],
      title: 'Customer service',
    },
    {
      links: [
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'landingPage',
            language: 'en-CA',
            id: 'd47cf139-0248-447b-be60-f19c46bcd9f4',
            uri: '/ca/about-us',
            version: { published: '2021-01-08T16:37:53.651347Z' },
            versionStatus: 'latest',
            slug: 'about-revitive',
          },
          title: 'About Revitive',
          entryTitle: 'About Revitive',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'contentPage',
            language: 'en-CA',
            id: '0c9fce46-5604-4723-9794-786e6c192105',
            uri: '/ca/can-i-use',
            version: { published: '2021-01-04T14:34:16.4437961Z' },
            versionStatus: 'latest',
            slug: 'can-i-use-revitive',
          },
          title: 'Can I Use Revitive?',
          entryTitle: 'Can I Use Revitive?',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'contentPage',
            language: 'en-CA',
            id: 'f03a19f0-83e2-43e5-95e0-9544fea91769',
            uri: '/ca/terms-of-use',
            version: { published: '2021-01-06T09:46:35.3955811Z' },
            versionStatus: 'latest',
            slug: 'website-usage-terms-conditions',
          },
          title: 'Website Usage Terms & Conditions',
          entryTitle: 'Website Usage Terms & Conditions',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'contentPage',
            language: 'en-CA',
            id: '331b80ee-5680-4d71-828d-478f6d2311ed',
            uri: '/ca/privacy-policy',
            version: { published: '2021-01-04T14:38:12.5726622Z' },
            versionStatus: 'latest',
            slug: 'privacy-policy',
          },
          title: 'Privacy Policy',
          entryTitle: 'Privacy Policy',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'contentPage',
            language: 'en-CA',
            id: 'b4b52916-e616-4529-9694-86a878d18c55',
            uri: '/ca/cookies',
            version: { published: '2021-01-04T14:37:33.4139065Z' },
            versionStatus: 'latest',
            slug: 'how-we-use-cookies',
          },
          title: 'How we use cookies',
          entryTitle: 'How we use cookies',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'contentPage',
            language: 'en-CA',
            id: 'cfc554d0-d281-4f1f-bb27-13f4fb30df27',
            uri: '/ca/accessibility',
            version: { published: '2021-01-12T12:17:31.7773209Z' },
            versionStatus: 'latest',
            slug: 'accessibility-guide',
          },
          title: 'Accessibility Guide',
          entryTitle: 'Accessibility Guide',
        },
        {
          sys: {
            dataFormat: 'entry',
            contentTypeId: 'landingPage',
            language: 'en-CA',
            id: '0dfd66ba-0782-4158-bae2-829b044bf04d',
            uri: '/ca/warranty-registration',
            version: { published: '2021-01-14T08:50:00.1234747Z' },
            versionStatus: 'latest',
            slug: 'register-warranty',
          },
          title: 'Register warranty',
          entryTitle: 'Register warranty',
        },
      ],
      title: 'Useful links',
    },
  ],
  sys: {
    dataFormat: 'entry',
    contentTypeId: 'siteConfig',
    language: 'en-CA',
    id: '18e08b13-9751-465b-9e95-66edd4ef9391',
    uri: null,
    version: { published: '2021-01-14T12:16:10.0262422Z' },
    versionStatus: 'latest',
    slug: 'global-site-configuration',
  },
  title: 'Global site configuration',
  contactDetails: {
    phone: '0800 014 6377',
    phoneLineTimes: 'Mon-Fri 8am-5:30pm, Sat 9am-4pm ',
    twitterLink: null,
    youTubeLink: null,
    facebookLink:
      'https://www.facebook.com/Revitive-LV-Canada-152762861578009/',
  },
  entryTitle: 'Global site configuration',
  splitPaymentsMinimumBasketValue: 50,
};
